" Turn syntax highlighting on
syntax on

" Use vanilla colors and adjust for Dark Terminals
colorscheme default
set background=dark

" Turn on search highlighting
set hlsearch

" Add numbers to each line on the left-hand side
set number

" Display tabs as " »", trailing Whitespaces as "◦", end-of-lines as "$"
set list
set listchars=tab:\ »,extends:›,precedes:‹,nbsp:·,trail:°,eol:$

" Set tabstops to 2 characters
set tabstop=2

" Expand tabstops to whitespaces
set expandtab

" Show filename in window title
set title

" CleanView for copy/paste
function! ToggleCleanView()
  if exists('b:clean_view_enabled') && b:clean_view_enabled
    set list
    set number
    set relativenumber
    let b:clean_view_enabled = 0
    echo "Clean view OFF"
  else
    set nolist
    set nonumber norelativenumber
    let b:clean_view_enabled = 1
    echo "Clean view ON"
  endif
endfunction
command! CleanView call ToggleCleanView()
